[package]
name = "using_slabs_decomposition"
version = "0.1.0"
authors = ["Artyom Gevorgyan <artemhevorhian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slice-group-by="0.2.6"
geo="0.13.0"